### ISSUE TITLE
Does not run the scheduler in background after closing app

### ISSUE THREAD

**Issue by zishanj** [JairAviles/AndroidJobDemo#2]
Your codes are great but its having one major issue. When you close the app, the rescheduling of job fails. The only solution is to execute `JobManager.ceate()` from `Application.onCreate()`. Do update me when you have a fix for this. :)

**Comment by JairAviles** [comment]
@zishanj Sorry for the delay in the response. I haven't been working on Android projects recently so that I am not focusing so much on it. I just want to know if you did uncomment the schedulePeriodic method and comment the request method.

https://github.com/JairAviles/AndroidJobDemo/blob/master/app/src/main/java/mx/jairaviles/androidevernotejobexample/main/MainActivity.kt#L27

**Comment by JairAviles** [comment]
Closed due to inactivity
